
locations = {
    'L1B_start_time_obs':                           ['/geolocation', -1, 'start_of_obs_time'],
    # 'L1B_centroid_time_obs':                      [''],
    'L1B_time_meas':                                ['/geolocation', -1, 'measurement_geolocation', -1, 'centroid_time'],
    'SCA_time_obs':                                 ['/sca_optical_properties', -1, 'starttime'],
    'ICA_time_obs':                                 ['/ica_optical_properties', -1, 'starttime'],
    'MCA_time_obs':                                 ['/mca_optical_properties', -1, 'starttime'],
    'group_start_time':                             ['/group_pcd', -1, 'starttime'],
    # 'group_end_time':                             [''],
    # 'group_centroid_time':                        [''],
    'longitude_of_DEM_intersection_meas':           ['/geolocation', -1, 'measurement_geolocation', -1, 'longitude_of_dem_intersection'],
    # 'longitude_of_DEM_intersection_obs':          [''],
    'latitude_of_DEM_intersection_meas':            ['/geolocation', -1, 'measurement_geolocation', -1, 'latgitude_of_dem_intersection'],
    # 'latitude_of_DEM_intersection_obs':           [''],
    'altitude_of_DEM_intersection_meas':            ['/geolocation', -1, 'measurement_geolocation', -1, 'altitude_of_dem_intersection'],
    # 'altitude_of_DEM_intersection_obs':           [''],
    'geoid_separation_obs':                         ['/geolocation', -1, 'geoid_separation'],
    'mie_altitude_meas':                            ['/geolocation', -1, 'measurement_geolocation', -1, 'mie_geolocation_height_bin[25]/altitude_of_height_bin'],
    # 'mie_altitude_obs':                           [''],
    'rayleigh_altitude_meas':                       ['/geolocation', -1, 'measurement_geolocation', -1, 'rayleigh_geolocation_height_bin[25]/altitude_of_height_bin'],
    # 'rayleigh_altitude_obs':                      [''],
    'SCA_middle_bin_altitude_obs':                  ['/sca_optical_properties', -1, 'geolocation_middle_bins', -1, 'altitude'],
    'group_middle_bin_start_altitude':              ['/group_optical_properties', -1, 'group_geolocation_middle_bins/start_altitude'],
    'group_middle_bin_stop_altitude':               ['/group_optical_properties', -1, 'group_geolocation_middle_bins/stop_altitude'],
    'group_start_obs':                              ['/group_pcd', -1, 'brc_start'],
    'group_start_meas_obs':                         ['/group_pcd', -1, 'measurement_start'],
    'group_end_obs':                                ['/group_pcd', -1, 'brc_end'],
    'group_end_meas_obs':                           ['/group_pcd', -1, 'measurement_end'],
    'group_height_bin_index':                       ['/group_pcd', -1, 'height_bin_index'],
    'L1B_num_of_meas_per_obs':                      ['/geolocation', -1, 'num_meas_eff'],

    'SCA_QC_flag':                                  ['/sca_pcd', -1, 'qc_flag'],
    'SCA_extinction_variance':                      ['/sca_pcd', -1, 'profile_pcd_bins', -1, 'extinction_variance'],
    'SCA_backscatter_variance':                     ['/sca_pcd', -1, 'profile_pcd_bins', -1, 'backscatter_variance'],
    'SCA_LOD_variance':                             ['/sca_pcd', -1, 'profile_pcd_bins', -1, 'lod_variance'],
    'SCA_middle_bin_extinction_variance':           ['/sca_pcd', -1, 'profile_pcd_mid_bins', -1, 'extinction_variance'],
    'SCA_middle_bin_backscatter_variance':          ['/sca_pcd', -1, 'profile_pcd_mid_bins', -1, 'backscatter_variance'],
    'SCA_middle_bin_LOD_variance':                  ['/sca_pcd', -1, 'profile_pcd_mid_bins', -1, 'lod_variance'],
    'SCA_middle_bin_BER_variance':                  ['/sca_pcd', -1, 'profile_pcd_mid_bins', -1, 'ber_variance'],
    'ICA_QC_flag':                                  ['/ica_pcd', -1, 'qc_flag'],
    'group_extinction_variance':                    ['/group_pcd', -1, 'particle_extinction_variance'],
    'group_backscatter_variance':                   ['/group_pcd', -1, 'particle_backscatter_variance'],
    'group_LOD_variance':                           ['/group_pcd', -1, 'particle_lod_variance'],
    'group_middle_bin_extinction_variance_top':     ['/group_pcd', -1, 'mid_particle_extinction_variance_top'],
    'group_middle_bin_backscatter_variance_top':    ['/group_pcd', -1, 'mid_particle_backscatter_variance_top'],
    'group_middle_bin_LOD_variance_top':            ['/group_pcd', -1, 'mid_particle_lod_variance_top'],
    'group_middle_bin_BER_variance_top':            ['/group_pcd', -1, 'mid_particle_ber_variance_top'],
    'group_middle_bin_extinction_variance_bottom':  ['/group_pcd', -1, 'mid_particle_extinction_variance_bot'],
    'group_middle_bin_backscatter_variance_bottom': ['/group_pcd', -1, 'mid_particle_backscatter_variance_bot'],
    'group_middle_bin_LOD_variance_bottom':         ['/group_pcd', -1, 'mid_particle_lod_variance_bot'],
    'group_middle_bin_BER_variance_bottom':         ['/group_pcd', -1, 'mid_particle_ber_variance_bot'],
    'SCA_extinction':                               ['/sca_optical_properties', -1, 'sca_optical_properties', -1, 'extinction'],
    'SCA_backscatter':                              ['/sca_optical_properties', -1, 'sca_optical_properties', -1, 'backscatter'],
    'SCA_LOD':                                      ['/sca_optical_properties', -1, 'sca_optical_properties', -1, 'lod'],
    'SCA_SR':                                       ['/sca_optical_properties', -1, 'sca_optical_properties', -1, 'sr'],
    'SCA_middle_bin_extinction':                    ['/sca_optical_properties', -1, 'sca_optical_properties_mid_bins', -1, 'extinction'],
    'SCA_middle_bin_backscatter':                   ['/sca_optical_properties', -1, 'sca_optical_properties_mid_bins', -1, 'backscatter'],
    'SCA_middle_bin_LOD':                           ['/sca_optical_properties', -1, 'sca_optical_properties_mid_bins', -1, 'lod'],
    'SCA_middle_bin_BER':                           ['/sca_optical_properties', -1, 'sca_optical_properties_mid_bins', -1, 'ber'],
    'ICA_filling_case':                             ['/ica_optical_properties', -1, 'ica_optical_properties', -1, 'case'],
    'ICA_extinction':                               ['/ica_optical_properties', -1, 'ica_optical_properties', -1, 'extinction'],
    'ICA_backscatter':                              ['/ica_optical_properties', -1, 'ica_optical_properties', -1, 'backscatter'],
    'ICA_LOD':                                      ['/ica_optical_properties', -1, 'ica_optical_properties', -1, 'lod'],
    'MCA_clim_BER':                                 ['/mca_optical_properties', -1, 'mca_optical_properties', -1, 'climber'],
    'MCA_extinction':                               ['/mca_optical_properties', -1, 'mca_optical_properties', -1, 'extinction'],
    'MCA_LOD':                                      ['/mca_optical_properties', -1, 'mca_optical_properties', -1, 'lod'],
    'group_extinction':                             ['/group_optical_properties', -1, 'group_optical_property/group_extinction'],
    'group_backscatter':                            ['/group_optical_properties', -1, 'group_optical_property/group_backscatter'],
    'group_LOD':                                    ['/group_optical_properties', -1, 'group_optical_property/group_lod'],
    'group_SR':                                     ['/group_optical_properties', -1, 'group_optical_property/group_sr'],
    'group_middle_bin_extinction_top':              ['/group_optical_properties', -1, 'group_optical_property_middle_bins/mid_extinction_top'],
    'group_middle_bin_backscatter_top':             ['/group_optical_properties', -1, 'group_optical_property_middle_bins/mid_backscatter_top'],
    'group_middle_bin_LOD_top':                     ['/group_optical_properties', -1, 'group_optical_property_middle_bins/mid_lod_top'],
    'group_middle_bin_BER_top':                     ['/group_optical_properties', -1, 'group_optical_property_middle_bins/mid_ber_top'],
    'group_middle_bin_extinction_bottom':           ['/group_optical_properties', -1, 'group_optical_property_middle_bins/mid_extinction_bot'],
    'group_middle_bin_backscatter_bottom':          ['/group_optical_properties', -1, 'group_optical_property_middle_bins/mid_backscatter_bot'],
    'group_middle_bin_LOD_bottom':                  ['/group_optical_properties', -1, 'group_optical_property_middle_bins/mid_lod_bot'],
    'group_middle_bin_BER_bottom':                  ['/group_optical_properties', -1, 'group_optical_property_middle_bins/mid_ber_bot'],
    'scene_classification_aladin_cloud_flag':       [''], # TODO: multiple possibilities: '/scene_classification', -1, 'aladin_cloud_flag/clrh', '/scene_classification', -1, 'aladin_cloud_flag/clsr', '/scene_classification', -1, 'aladin_cloud_flag/downclber', '/scene_classification', -1, 'aladin_cloud_flag/topclber'
    'scene_classification_NWP_cloud_flag':          ['/scene_classification', -1, 'nwp_cloud_flag'],
    'scene_classification_group_class_reliability': ['/scene_classification', -1, 'l2a_group_class_reliability'],
}
