# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0003_auto_20200131_1229'),
        ('coverages', '0007_auto_20200131_1229'),
        ('aeolus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedProductDataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1024)),
                ('format', models.CharField(blank=True, max_length=64, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_data_item', to='coverages.Product')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backends.Storage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
