name: CI
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # get branch/tag name for later stages
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_BRANCH::$([[ $GITHUB_REF == refs/heads/* ]] && echo ${GITHUB_REF#refs/heads/} || echo "")
          echo ::set-output name=SOURCE_TAG::$([[ $GITHUB_REF == refs/tags/* ]] && echo ${GITHUB_REF#refs/tags/} || echo "")

      - name: Build the aeolus-client docker image and tag it with the branch name
        # TODO handle tag pushes
        run: |
          docker build -t eoxa/aeolus-server:${{ steps.branch_name.outputs.SOURCE_BRANCH }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: success()

      - name: Push docker image(s)
        run: docker push eoxa/aeolus-server
        if: success()
